version: "3.9"
services:
  db:
    image: postgres:14
    container_name: go-realworld
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d/
